name: Test the generation of test matrices pages

# Controls when the action will run.
on:
  pull_request:
    branches:
      - main
jobs:
  test-generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Generate the test matrix 🔧
        run: |
          export CI_DASHBOARD_DAILYMATRIX_TEST_HISTORY=3
          make generate_daily_matrix
          make static

      - name: 'Attach output to the presubmit job'
        uses: actions/upload-artifact@v4
        with:
          name: gpu-operator-daily-matrix
          path: output/gpu-operator_daily-matrix.html
